apiVersion: v1
kind: Service
metadata: 
  name: conversaopeso
spec:
  selector:
    app: conversaopeso
  ports:
   - port: 80
     protocol: TCP
     name: ui
     nodePort: 30000
  type: NodePort
  #type: ClusterIP
 